apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservices
  labels:
    app: webby
spec:
  selector:
    matchLabels:
      app: webby
  replicas: 3
  template:
    metadata:
      labels:
        app: webby
    spec:
      containers:
      - name: webby  
        image: bhcd.registry/alta3-webby
        ports:
        - containerPort: 8888   

